language: python
python:
  - "2.7"
  - "2.6"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"

install: "pip install -r requirements.txt"

script: nosetests --with-coverage --cover-package=pyredux --cover-html ./pyredux/Test/
